### ISSUE TITLE
Proper merge and compaction lacking time stamp?

### ISSUE THREAD

**Issue by scottcagno** [krasun/lsmtree#9]
Just wondering how proper merge and compaction can take place without time stamp data being encoded to the disc table?

I would be more than happy too help out with this project if you are looking for participants.

**Comment by krasun** [comment]
Hi, @scottcagno! Thanks for showing interest in the project. 

There is no problem in merging and compacting entries since I store them already in a sorted manner. Start from this function: 
https://github.com/krasun/lsmtree/blob/4a019b10cac8b67cace16973dd4db043ab13b0e1/merge.go#L15 and then look at https://github.com/krasun/lsmtree/blob/4a019b10cac8b67cace16973dd4db043ab13b0e1/merge.go#L64. It looks pretty messy. 

I have a simple test for the merge https://github.com/krasun/lsmtree/blob/4a019b10cac8b67cace16973dd4db043ab13b0e1/merge_test.go#L12 that covers most of the cases, but I still need to test it better.

The idea behind the merge (without timestamps) is straightforward. Imagine that we have two disk tables with keys and values: `{1=val1, 4=val2, 5=val3}` and `{2=val4, 3=val5, 5=val6, 7=val7}`. You need to iterate over both of them and create a new disk table by inserting keys in a sorted manner. If you encounter the same key, you discard the older one.  
`{1=val1, 2=val4, 3=val5, 4=val2, 5=val6, 7=val7}`. 

You do not need a timestamp there, and it is like [Merge sort](https://en.wikipedia.org/wiki/Merge_sort). I hope I answered your question. 

About any help with this project, it depends on your goals and desires. I do not object if you join the project, but I need to be honest that my main goal is to improve my understanding of how databases work at a low level. 

The final destination is to build a fully working database that supports SQL queries, LSM tree, and [B+ tree](https://github.com/krasun/fbptree) as storage engines. Now, I am working on the latter.

So, yes, if you see how you can help with this, I won't object. A lot of improvements can be made!
